# Jekyll configuration
markdown: kramdown
highlighter: rouge
language: 'en-us'

baseurl: ''

title: Abhishek Paudel
description: Computer Engineer | AI and Machine Learning Enthusiast
author: Abhishek Paudel
cover: assets/img/blog-cover.jpg
logo_dark: assets/img/favicon.png
favicon: assets/img/favicon.png
production_url: https://apaudel.com.np/
source_url: https://github.com/abpaudel/abpaudel.github.io/
CNAME: apaudel.com.np

navigation: True
subscribers: False

twitter: abpaudel
github: abpaudel
instagram: abpaudel
linkedin: abpaudel

disqus: True
disqus_shortname: abpaudel

google_analytics:  UA-52700205-1

permalink: /blog/:slug/

paginate: 6
paginate_path: /blog/page/:num/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

feed:
  path: feed.xml

defaults:
  - scope:
      path:            "assets"
    values:
      sitemap:         false
  - scope:
      path:            "cv"
    values:
      sitemap:         false
  - scope:
      path:            "blog/page"
    values:
      sitemap:         false

exclude:
  - assets/css
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - changelog.md
  - "*.Rmd"
  - .git*
